from arango import ArangoClient
import base64

encodedCA = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHVENDQWdHZ0F3SUJBZ0lSQU1VZlRqcDdieElvN043aFpSL2lWK1V3RFFZSktvWklodmNOQVFFTEJRQXcKSmpFUk1BOEdBMVVFQ2hNSVFYSmhibWR2UkVJeEVUQVBCZ05WQkFNVENFRnlZVzVuYjBSQ01CNFhEVEkyTURneApPVEV5TlRnMU0xb1hEVE14TURneE9ERXlOVGcxTTFvd0pqRVJNQThHQTFVRUNoTUlRWEpoYm1kdlJFSXhFVEFQCkJnTlZCQU1UQ0VGeVlXNW5iMFJDTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEKK1Zqd1FYMFhBMXJhTFIxWHoyRGNoODNjcEtxWmE0clEyTXM5SUl2L0FHTUFOa25FYTZ1RFNIaE1weXk1TURRQwpreWFDRWJJQTJIcmNtaU05RDQ1WjJiNWJZMXc0WmZMRWlob1JYMURKTGFZVnU0QW5qRTVYWnQ4eExNV2pwcEl2Cmd3NXdralF4RzFVN2ZCUGw0UmV3cDJVQU9xTklaM21XZUlvaXo4SURMZmd5Z1hIUmQwamxqK0pmRkV4QlFkNm4KUHZnUGRXNnl0cDBjZlBaZk9rc05hcWZ0T25aRXdRaEZ6NE1yN0kyRm9aUWFvei93QkE2NmVrSTBpOEtIcmppdwpkRFpVTDRUU25ZYkUzbGlLalVicDY3NnRCTnNMMElXbml3dTl4VnYyN2V0bm9mVjE3ZnhXMHdjWWU2Zjg0TWV4CmxrdGgrQm4xQm5TY1R6QmN1Tkw2VndJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFQKQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVREWVh4VGJ6aU5GUTVFd1RNUS9RenBPK040NHdEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQUNJcGRFa0c0cklDWmZTOEFlV2dqazJ1QnU3elhJRjNpcnp0T2JTUHNoMVFYU0dOCkk3dGJOeWhpWWFWcVlGdzNNQXAyazFHeTkxcThFR3hwVVpsUWI3L0JxeUhqSTZpZGVVbWJDbGNTcVJzZDhqR2YKRG95ZmpVM0RPMUIrYmNwbGlabW81YzM4bUU5SzBsT3d4dnhGTEp3dGNxQVBCdm94aWxaSDBNR3lwS096eUNBSgpSN1JIVmJoZEMySGtONHA4NDVHcjhjK2pzMzN1bE9icjRFTTJzUmRrdDd6ME5YQW1TNDcvTkZOS2V5dWJYY2lmCkdZVm9qVk5pMk9HRGdWejRtUE03ajdWdGpmcSswaTBXWUh0SUF4QVh2R2kyc0thNmFsdlZhZUpGN3A4aFYvdXkKakpsWUw4b3RuVHpJSDdtSTgrc2hTYjNuMURzNWlHcDQwY2ZLNXdrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
try:
    file_content = base64.b64decode(encodedCA)
    with open("cert_file.crt", "w+") as f:
        f.write(file_content.decode("utf-8"))
except Exception as e:
    print(str(e))
    exit(1)

client = ArangoClient(
    hosts="https://21880139cba6.arangodb.cloud:18529", verify_override="cert_file.crt"
)

sys_db = client.db("_system", username="root", password="KpTfBKf6YwklvsUKIfzO")

# Note that ArangoGraph Insights Platform runs deployments in a cluster configuration.
# To achieve the best possible availability, your client application has to handle
# connection failures by retrying operations if needed.
print("ArangoDB:", sys_db.version())
